js = '''
{"input":{"value":"3.26","isFrom":true,"fromCurrency":"GEL","toCurrency":"EUR"},"currency":{"timestamp":"2019-09-24T15:54:10.000Z",
"baseCurrency":"USD","exchangeRates":{
"FJD":2.18185,
"DJF":177.720276,
"AED":3.672974,
"SVC":8.749303,
"MZN":61.859744,
"ISK":124.739676,
"CHF":0.98728,
"HRK":6.73125,
"ERN":14.999823,
"ALL":110.604833,
"TWD":31.051048,
"RWF":920,
"JMD":135.060262,
"HKD":7.840797,
"MWK":721.524985,
"LVL":0.60489,
"SCR":13.730996,
"QAR":3.641007,
"EUR":0.909195,
"ARS":56.927505,
"MXN":19.453197,
"STD":21560.79,
"RSD":106.830229,
"BBD":2.0188,
"DKK":6.78774,
"GTQ":7.723901,
"COP":3439.45,
"TTD":6.77335,
"KMF":447.624999,
"ZMW":13.023991,
"LTL":2.95274,
"SAR":3.750974,
"CDF":1664.999758,
"KZT":386.830382,
"DOP":52.149791,
"SRD":7.458038,
"SZL":14.889748,
"LSL":14.890271,
"HNL":24.697336,
"UGX":3675.449766,
"MYR":4.181404,
"USD":1,
"MKD":55.987027,
"YER":250.299624,
"XDR":0.73055,
"CAD":1.325115,
"CLP":723.125024,
"MGA":3784.889513,
"IRR":42104.999904,
"BGN":1.778298,
"AFN":78.282409,
"MVR":15.410565,
"TND":2.8601,
"NOK":9.00547,
"SYP":515.000111,
"MRO":357.000346,
"MUR":36.380053,
"FKP":0.80432,
"ZAR":14.92515,
"MMK":1532.305345,
"EEK":14.360393,
"VND":23208.5,
"XAU":0.000655,
"BZD":2.015403,
"IMP":0.801613,
"TZS":2298.587009,
"INR":70.944702,
"THB":30.540255,
"XPF":108.999876,
"CNY":7.116494,
"UZS":9410.000319,
"DZD":120.285054,
"MOP":8.07325,
"GEL":2.965022,
"GIP":0.80435,
"EGP":16.319657,
"BAM":1.779698,
"XOF":596.910003,
"ZWL":322.000001,
"SGD":1.376503,
"MAD":9.682302,
"AUD":1.472097,
"NPR":113.59009,
"GGP":0.801613,
"ILS":3.499499,
"KRW":1196.820158,
"PAB":0.9998,
"NAD":14.890189,
"RON":4.31725,
"CUC":1,
"BTC":0.000105,
"UYU":36.770325,
"AWG":1.8,
"BDT":84.483015,
"GYD":208.610183,
"PLN":3.982598,
"CVE":101.079934,
"GHS":5.510121,
"KPW":900.058608,
"SLL":9400.000146,
"ETB":29.3865,
"AOA":371.367965,
"BSD":0.99985,
"LKR":181.160137,
"MNT":2667.491706,
"JPY":107.284019,
"PGK":3.385,
"CRC":580.575014,
"NIO":33.650111,
"OMR":0.385045,
"CZK":23.515975,
"TOP":2.326197,
"BOB":6.91395,
"MDL":17.733005,
"NGN":361.000147,
"JEP":0.801613,
"KHR":4107.000522,
"GBP":0.801396,
"AZN":1.704989,
"SBD":8.275897,
"SDG":45.106502,
"KYD":0.83325,
"LAK":8819.999879,
"LYD":1.405027,
"SOS":579.999965,
"VUV":118.013745,
"PKR":156.519497,
"KGS":69.824199,
"IDR":14123.4,
"BYN":2.06265,
"VEF":9.987505,
"KWD":0.3038,
"WST":2.68455,
"PHP":52.230188,
"BND":1.350901,
"AMD":476.109472,
"ZMK":9001.198214,
"NZD":1.58305,
"SEK":9.69374,
"HUF":303.77021,
"PEN":3.346798,
"BMD":1,
"KES":103.810123,
"XCD":2.70255,
"LBP":1507.999878,
"ANG":1.7648,
"SHP":1.320896,
"HTG":95.736983,
"TMT":3.51,
"TRY":5.702302,
"BWP":10.952017,
"BYR":19600,
"IQD":1191,
"BRL":4.171903,
"BTN":70.99395,
"UAH":24.23027,
"TJS":9.68865,
"CLF":0.02621,
"XAF":596.839887,
"GMD":50.325026,
"BHD":0.377025,
"CUP":26.5,
"XAG":0.053875,
"PYG":6381.624357,
"LRD":208.399855,
"GNF":9230.000227,
"BIF":1860,
"RUB":63.848699,
"JOD":0.709028}},
"routing":{"locationBeforeTransitions":{"pathname":"/","search":"?amount=3.26&from=GEL&to=EUR","hash":"","action":"POP","key":null,"query":{"amount":"3.26","from":"GEL","to":"EUR"}}},"i18n":{"locale":"en","translations":{"app":{"title":"Valuta - Currency converter","description":"A simple and intuitive currency converter, perfect for travelers. Valuta provides accurate exchange rates for over 160 world currencies!"},"home":{"title":"Valuta","subtitle":"Currency converter","description":"A simple and intuitive currency converter, perfect for travelers. Valuta provides accurate exchange rates for over 160 world currencies!","description2":"Valuta is a must-have especially for people that travels a lot and need a fast way to know updated exchange rates.","exchangeRate1":"Exchange rate","exchangeRate2":"updated"},"currencySelect":{"search":"\"EUR\", \"Euro\", \"Italy\""},
"generic":{"currencyDetails":{
"FJD":{"name":"Fijian dollar","countries":"Fiji","symbol":"$","priority":1},
"DJF":{"name":"Djiboutian franc","countries":"Djibouti","symbol":"Fr","priority":1},
"AED":{"name":"UAE dirham","countries":"United Arab Emirates","symbol":"د.إ","priority":1},
"SVC":{"name":"Salvadoran Colón","countries":"El Salvador","symbol":"$","priority":1},
"MZN":{"name":"Mozambican metical","countries":"Mozambique","symbol":"MT","priority":1},
"ISK":{"name":"Icelandic krona","countries":"Iceland","symbol":"kr","priority":1},
"CHF":{"name":"Swiss franc","countries":["Liechtenstein","Switzerland"],"symbol":"Fr","priority":996},
"HRK":{"name":"Croatian kuna","countries":"Croatia","symbol":"kn","priority":1},
"ERN":{"name":"Eritrean nakfa","countries":"Eritrea","symbol":"Nfk","priority":1},
"ALL":{"name":"Albanian lek","countries":"Albania","symbol":"L","priority":1},
"TWD":{"name":"New Taiwan dollar","countries":"Taiwan","symbol":"$","priority":1},
"RWF":{"name":"Rwandan franc","countries":"Rwanda","symbol":"Fr","priority":1},
"JMD":{"name":"Jamaican dollar","countries":"Jamaica","symbol":"$","priority":1},
"HKD":{"name":"Hong Kong dollar","countries":"Hong Kong","symbol":"$","priority":1},
"MWK":{"name":"Malawian kwacha","countries":"Malawi","symbol":"MK","priority":1},
"LVL":{"name":"Latvian Lats","countries":"Latvia","symbol":"Ls","priority":1},
"SCR":{"name":"Seychellois rupee","countries":"Seychelles","symbol":"Rs","priority":1},
"QAR":{"name":"Qatari riyal","countries":"Qatar","symbol":"ر.ق","priority":1},
"EUR":{"name":"European euro","countries":["Akrotiri and Dhekelia","Aland Islands","Andorra","Austria","Belgium","Cyprus","Estonia","Finland","France","French Guiana","Germany","Greece","Guadeloupe","Ireland","Italy","Kosovo","Latvia","Lithuania","Luxembourg","Malta","Martinique","Mayotte","Monaco","Montenegro","Netherlands","Portugal","Reunion","Saint Barthelemy","Saint Martin","Saint Pierre and Miquelon","San Marino","Slovakia","Slovenia","Spain","Vatican City"],"symbol":"€","priority":998},
"ARS":{"name":"Argentine peso","countries":"Argentina","symbol":"$","priority":1},
"MXN":{"name":"Mexican peso","countries":"Mexico","symbol":"$","priority":1},
"STD":{"name":"Sao Tome and Principe dobra","countries":"Sao Tome and Principe","symbol":"Db","priority":1},
"RSD":{"name":"Serbian dinar","countries":"Serbia","symbol":"дин.","priority":1},
"BBD":{"name":"Barbadian dollar","countries":"Barbados","symbol":"$","priority":1},
"DKK":{"name":"Danish krone","countries":["Denmark","Greenland"],"symbol":"kr","priority":1},
"GTQ":{"name":"Guatemalan quetzal","countries":"Guatemala","symbol":"Q","priority":1},
"COP":{"name":"Colombian peso","countries":"Colombia","symbol":"$","priority":1},
"TTD":{"name":"Trinidad and Tobago dollar","countries":"Trinidad and Tobago","symbol":"$","priority":1},
"KMF":{"name":"Comorian franc","countries":"Comoros","symbol":"Fr","priority":1},
"ZMW":{"name":"Zambian kwacha","countries":"Zambia","symbol":"ZK","priority":1},
"LTL":{"name":"Lithuanian Litas","countries":"Lithuania","symbol":"Lt","priority":1},
"SAR":{"name":"Saudi Arabian riyal","countries":"Saudi Arabia","symbol":"ر.س","priority":1},
"CDF":{"name":"Congolese franc","countries":["Congo","Democratic Republic of the"],"symbol":"Fr","priority":1},
"KZT":{"name":"Kazakhstani tenge","countries":"Kazakhstan","symbol":"лв","priority":1},
"DOP":{"name":"Dominican peso","countries":"Dominican Republic","symbol":"$","priority":1},
"SRD":{"name":"Surinamese dollar","countries":"Suriname","symbol":"£","priority":1},
"SZL":{"name":"Swazi lilangeni","countries":"Swaziland","symbol":"L","priority":1},
"LSL":{"name":"Lesotho loti","countries":"Lesotho","symbol":"L","priority":1},
"HNL":{"name":"Honduran lempira","countries":"Honduras","symbol":"L","priority":1},
"UGX":{"name":"Ugandan shilling","countries":"Uganda","symbol":"Sh","priority":1},
"MYR":{"name":"Malaysian ringgit","countries":"Malaysia","symbol":"RM","priority":1},
"USD":{"name":"United States dollar","countries":["American Samoa","USA","Bonaire","British Indian Ocean Territory","British Virgin Islands","Caribbean Netherlands","Ecuador","El Salvador","Guam","Marshall Islands","Micronesia","Northern Mariana Islands","Palau","Panama","Puerto Rico","Saba","Sint Eustatius","Timor-Leste","Turks and Caicos Islands","United States of America","US Virgin Islands","Wake Island","Zimbabwe"],"symbol":"$","priority":999},
"MKD":{"name":"Macedonian denar","countries":"Macedonia","symbol":"ден","priority":1},
"YER":{"name":"Yemeni rial","countries":"Yemen","symbol":"﷼","priority":1},
"XDR":{"name":"IMF Special Drawing Rights","countries":"International Monetary Fund","symbol":"SDR","priority":1},
"CAD":{"name":"Canadian dollar","countries":"Canada","symbol":"$","priority":1},
"CLP":{"name":"Chilean peso","countries":"Chile","symbol":"$","priority":1},
"MGA":{"name":"Malagasy ariary","countries":"Madagascar","symbol":"Ar","priority":1},
"IRR":{"name":"Iranian rial","countries":"Iran","symbol":"﷼","priority":1},
"BGN":{"name":"Bulgarian lev","countries":"Bulgaria","symbol":"лв","priority":1},
"AFN":{"name":"Afghan afghani","countries":"Afghanistan","symbol":"؋","priority":1},
"MVR":{"name":"Maldivian rufiyaa","countries":"Maldives","symbol":"Rf","priority":1},
"TND":{"name":"Tunisian dinar","countries":"Tunisia","symbol":"د.ت","priority":1},
"NOK":{"name":"Norwegian krone","countries":["Norway","Svalbard and Jan Mayen"],"symbol":"kr","priority":1},
"SYP":{"name":"Syrian pound","countries":"Syria","symbol":"£","priority":1},
"MRO":{"name":"Mauritanian ouguiya","countries":"Mauritania","symbol":"UM","priority":1},
"MUR":{"name":"Mauritian rupee","countries":"Mauritius","symbol":"₨","priority":1},
"FKP":{"name":"Falkland Islands pound","countries":"Falkland Islands","symbol":"£","priority":1},
"ZAR":{"name":"South African rand","countries":"South Africa","symbol":"R","priority":1},
"MMK":{"name":"Myanmar kyat","countries":"Myanmar (Burma)","symbol":"Ks","priority":1},
"EEK":{"name":"Estonian Kroon","countries":"Estonia","symbol":"kr","priority":1},
"VND":{"name":"Vietnamese dong","countries":"Vietnam","symbol":"₫","priority":1},
"XAU":{"name":"Gold Ounce","countries":"","symbol":"XAU","priority":1},
"BZD":{"name":"Belize dollar","countries":"Belize","symbol":"$","priority":1},
"IMP":{"name":"Manx pound","countries":"Isle of Man","symbol":"£","priority":1},
"TZS":{"name":"Tanzanian shilling","countries":"Tanzania","symbol":"Sh","priority":1},
"INR":{"name":"Indian rupee","countries":["India","Buthan"],"symbol":"₹","priority":1},
"THB":{"name":"Thai baht","countries":"Thailand","symbol":"฿","priority":1},
"XPF":{"name":"CFP franc","countries":["French Polynesia","New Caledonia","Wallis and Futuna"],"symbol":"Fr","priority":1},
"CNY":{"name":"Chinese Yuan Renminbi","countries":"China","symbol":"¥","priority":995},
"UZS":{"name":"Uzbekistani som","countries":"Uzbekistan","symbol":"лв","priority":1},
"DZD":{"name":"Algerian dinar","countries":"Algeria","symbol":"د.ج","priority":1},
"MOP":{"name":"Macanese pataca","countries":"Macau (China)","symbol":"P","priority":1},
"GEL":{"name":"Georgian lari","countries":"Georgia","symbol":"₾","priority":1},
"GIP":{"name":"Gibraltar pound","countries":"Gibraltar","symbol":"£","priority":1},
"EGP":{"name":"Egyptian pound","countries":"Egypt","symbol":"£","priority":1},
"BAM":{"name":"Bosnian Convertible Marka","countries":"Bosnia and Herzegovina","symbol":"KM","priority":1},
"XOF":{"name":"West African CFA franc","countries":["Benin","Burkina Faso","Cote d'Ivoire","Guinea-Bissau","Qatar","Niger","Senegal","Togo"],"symbol":"Fr","priority":1},
"ZWL":{"name":"Zimbabwean dollar","countries":"Zimbabwe","symbol":"Rs","priority":1},
"SGD":{"name":"Singapore dollar","countries":"Singapore","symbol":"$","priority":1},
"MAD":{"name":"Moroccan dirham","countries":"Morocco","symbol":"د.م.","priority":1},
"AUD":{"name":"Australian dollar","countries":["Australia","Christmas Island","Cocos Islands","Kiribati","Nauru","Norfolk Island","Tuvalu"],"symbol":"$","priority":1},
"NPR":{"name":"Nepalese rupee","countries":"Nepal","symbol":"Rs","priority":1},
"GGP":{"name":"Guernsey Pound","countries":"Guernsey","symbol":"£","priority":1},
"ILS":{"name":"Israeli new shekel","countries":["Israel","Palestine"],"symbol":"₪","priority":1},
"KRW":{"name":"South Korean won","countries":"South Korea","symbol":"₩","priority":1},
"PAB":{"name":"Panamanian Balboa","countries":"Panama","symbol":"B/.","priority":1},
"NAD":{"name":"Namibian dollar","countries":"Namibia","symbol":"$","priority":1},
"RON":{"name":"Romanian leu","countries":"Romania","symbol":"lei","priority":1},
"CUC":{"name":"Cuban Convertible Peso","countries":"Cuba","symbol":"$","priority":1},
"BTC":{"name":"Bitcoin","countries":"","symbol":"Ƀ","priority":1},
"UYU":{"name":"Uruguayan peso","countries":"Uruguay","symbol":"$","priority":1},
"AWG":{"name":"Aruban florin","countries":"Aruba (Netherlands)","symbol":"ƒ","priority":1},
"BDT":{"name":"Bangladeshi taka","countries":"Bangladesh","symbol":"৳","priority":1},
"GYD":{"name":"Guyanese dollar","countries":"Guyana","symbol":"$","priority":1},
"PLN":{"name":"Polish zloty","countries":"Poland","symbol":"zł","priority":1},
"CVE":{"name":"Cape Verdean escudo","countries":"Cabo Verde","symbol":"Esc","priority":1},
"GHS":{"name":"Ghanaian cedi","countries":"Ghana","symbol":"₵","priority":1},
"KPW":{"name":"North Korean won","countries":"North Korea","symbol":"₩","priority":1},
"SLL":{"name":"Sierra Leonean leone","countries":"Sierra Leone","symbol":"Le","priority":1},
"ETB":{"name":"Ethiopian birr","countries":"Ethiopia","symbol":"Br","priority":1},
"AOA":{"name":"Angolan kwanza","countries":"Angola","symbol":"Kz","priority":1},
"BSD":{"name":"Bahamian dollar","countries":"Bahamas","symbol":"$","priority":1},
"LKR":{"name":"Sri Lankan rupee","countries":"Sri Lanka","symbol":"Rs","priority":1},
"MNT":{"name":"Mongolian tugrik","countries":"Mongolia","symbol":"₮","priority":1},
"JPY":{"name":"Japanese yen","countries":"Japan","symbol":"¥","priority":1},
"PGK":{"name":"Papua New Guinean kina","countries":"Papua New Guinea","symbol":"K","priority":1},
"CRC":{"name":"Costa Rican colon","countries":"Costa Rica","symbol":"₡","priority":1},
"NIO":{"name":"Nicaraguan cordoba","countries":"Nicaragua","symbol":"C$","priority":1},
"OMR":{"name":"Omani rial","countries":"Oman","symbol":"ر.ع.","priority":1},
"CZK":{"name":"Czech koruna","countries":"Czech Republic","symbol":"Kč","priority":1},
"TOP":{"name":"Tongan pa’anga","countries":"Tonga","symbol":"T$","priority":1},
"BOB":{"name":"Bolivian boliviano","countries":"Bolivia","symbol":"Bs.","priority":1},
"MDL":{"name":"Moldovan leu","countries":"Moldova","symbol":"L","priority":1},
"NGN":{"name":"Nigerian naira","countries":"Nigeria","symbol":"₦","priority":1},
"JEP":{"name":"Jersey pound","countries":"Jersey","symbol":"£","priority":1},
"KHR":{"name":"Cambodian riel","countries":"Cambodia","symbol":"៛","priority":1},
"GBP":{"name":"Pound sterling","countries":["South Georgia Island","Tristan da Cunha","United Kingdom"],"symbol":"£","priority":997},
"AZN":{"name":"Azerbaijani manat","countries":"Azerbaijan","symbol":"₼","priority":1},
"SBD":{"name":"Solomon Islands dollar","countries":"Solomon Islands","symbol":"$","priority":1},
"SDG":{"name":"Sudanese pound","countries":"Sudan","symbol":"ج.س.","priority":1},
"KYD":{"name":"Cayman Islands dollar","countries":"Cayman Islands","symbol":"$","priority":1},
"LAK":{"name":"Lao kip","countries":"Laos","symbol":"₭","priority":1},
"LYD":{"name":"Libyan dinar","countries":"Libya","symbol":"ل.د","priority":1},
"SOS":{"name":"Somali shilling","countries":"Somalia","symbol":"Sh","priority":1},
"VUV":{"name":"Vanuatu vatu","countries":"Vanuatu","symbol":"Vt","priority":1},
"PKR":{"name":"Pakistani rupee","countries":"Pakistan","symbol":"Rs","priority":1},
"KGS":{"name":"Kyrgyzstani som","countries":"Kyrgyzstan","symbol":"лв","priority":1},
"IDR":{"name":"Indonesian rupiah","countries":"Indonesia","symbol":"Rp","priority":1},
"VEF":{"name":"Venezuelan bolivar","countries":"Venezuela","symbol":"Bs.","priority":1},
"KWD":{"name":"Kuwaiti dinar","countries":"Kuwait","symbol":"د.ك","priority":1},
"WST":{"name":"Samoan tala","countries":"Samoa","symbol":"T","priority":1},
"PHP":{"name":"Philippine peso","countries":"Philippines","symbol":"₱","priority":1},
"BND":{"name":"Brunei dollar","countries":"Brunei","symbol":"$","priority":1},
"AMD":{"name":"Armenian dram","countries":"Armenia","symbol":"AMD","priority":1},
"ZMK":{"name":"Zambian Kwacha","countries":"Zambia","symbol":"ZK","priority":1},
"NZD":{"name":"New Zealand dollar","countries":["New Zealand","Niue","Pitcairn Islands","Tokelau"],"symbol":"$","priority":1},
"SEK":{"name":"Swedish krona","countries":"Sweden","symbol":"kr","priority":1},
"HUF":{"name":"Hungarian forint","countries":"Hungary","symbol":"Ft","priority":1},
"PEN":{"name":"Peruvian sol","countries":"Peru","symbol":"S/.","priority":1},
"BMD":{"name":"Bermudian dollar","countries":"Bermuda","symbol":"$","priority":1},
"KES":{"name":"Kenyan shilling","countries":"Kenya","symbol":"Sh","priority":1},
"XCD":{"name":"East Caribbean dollar","countries":["Anguilla","Uk","Antigua and Barbuda","Grenada","Montserrat","Saint Kitts and Nevis","Saint Lucia","Saint Vincent and the Grenadines"],"symbol":"$","priority":1},
"LBP":{"name":"Lebanese pound","countries":"Lebanon","symbol":"ل.ل","priority":1},
"ANG":{"name":"Netherlands Antillean guilder","countries":["Curacao","Sint Maarten"],"symbol":"ƒ","priority":1},
"SHP":{"name":"Saint Helena pound","countries":["Ascension Island","Saint Helena"],"symbol":"£","priority":1},
"HTG":{"name":"Haitian gourde","countries":"Haiti","symbol":"G","priority":1},
"TMT":{"name":"Turkmen manat","countries":"Turkmenistan","symbol":"m","priority":1},
"TRY":{"name":"Turkish lira","countries":"Turkey","symbol":"₺","priority":1},
"BWP":{"name":"Botswana pula","countries":"Botswana","symbol":"P","priority":1},
"BYR":{"name":"Belarusian Ruble","countries":"Belarus","symbol":"Br","priority":1},
"IQD":{"name":"Iraqi dinar","countries":"Iraq","symbol":"ع.د","priority":1},
"BRL":{"name":"Brazilian real","countries":"Brazil","symbol":"R$","priority":1},
"BTN":{"name":"Bhutanese ngultrum","countries":"Bhutan","symbol":"Nu.","priority":1},
"UAH":{"name":"Ukrainian hryvnia","countries":"Ukraine","symbol":"₴","priority":1},
"TJS":{"name":"Tajikistani somoni","countries":"Tajikistan","symbol":"SM","priority":1},
"CLF":{"name":"Chilean Unidad de Fomento","countries":"Chile","symbol":"$","priority":1},
"XAF":{"name":"Central African CFA franc","countries":["Cameroon","Central African Republic","Chad","Republic of the Congo","Equatorial Guinea","Gabon"],"symbol":"Fr","priority":1},
"GMD":{"name":"Gambian dalasi","countries":"Gambia","symbol":"D","priority":1},
"BHD":{"name":"Bahraini dinar","countries":"Bahrain","symbol":".د.ب","priority":1},
"CUP":{"name":"Cuban peso","countries":"Cuba","symbol":"$","priority":1},
"XAG":{"name":"Silver Ounce","countries":"","symbol":"XAG","priority":1},
"PYG":{"name":"Paraguayan guarani","countries":"Paraguay","symbol":"₲","priority":1},
"LRD":{"name":"Liberian dollar","countries":"Liberia","symbol":"$","priority":1},
"GNF":{"name":"Guinean franc","countries":"Guinea","symbol":"Fr","priority":1},
"BIF":{"name":"Burundi franc","countries":"Burundi","symbol":"Fr","priority":1},
"RUB":{"name":"Russian ruble","countries":"Russia","symbol":"₽","priority":1},
"JOD":{"name":"Jordanian dinar","countries":"Jordan","symbol":"د.ا","priority":1}
}
'''
